import sublime, sublime_plugin, subprocess

class contextual_help_xys(sublime_plugin.TextCommand):
	def run(self, edit):
		xypath = self.view.settings().get('xypath')
		CursorLocation = self.view.sel()[0]
		ScopeName = self.view.scope_name(CursorLocation.a).strip()
		ScopeText = self.view.substr(self.view.extract_scope(CursorLocation.a))
		if ScopeName == "source.xys entity.name.function.UDF.xys":
			# need to handle namespaces
			self.view.window().run_command('goto_definition')
		elif ScopeName == "source.xys string":
		 	self.view.window().run_command('goto_definition') # goto subscript symbol
		elif ScopeName == "source.xys entity.name.function.xys":
			# ScopeText = ScopeText.replace("#", "_")
			arg = xypath + "\\XYplorer.chm::/idh_scripting_comref.htm#idh_sc_" + ScopeText
			subprocess.Popen(["hh.exe", arg])
		elif ScopeName == "source.xys variable.parameter.xys":
			subprocess.Popen(["hh.exe", xypath + "\\XYplorer.chm::/idh_scripting.htm#idh_scripting_variables"])
		elif ScopeName == "source.xys variable.parameter.native.xys":
			subprocess.Popen(["hh.exe", xypath + "\\XYplorer.chm::/idh_variables.htm"])
		elif ScopeName == "source.xys keyword.operator":
			subprocess.Popen(["hh.exe", xypath + "\\XYplorer.chm::/idh_scripting.htm#idh_scripting_operatorprecedence"])
		elif ScopeName == "source.xys string.unquoted.heredoc":
			subprocess.Popen(["hh.exe", xypath + "\\XYplorer.chm::/idh_scripting.htm#idh_scripting_heredoc"])
		elif ScopeName == "source.xys string.unquoted.nowdoc":
			subprocess.Popen(["hh.exe", xypath + "\\XYplorer.chm::/idh_scripting.htm#idh_scripting_heredoc"])
		elif ScopeName == "source.xys keyword.control.xys":
			ScopeTextLower = ScopeText.lower()
			if ScopeTextLower == "if" or ScopeTextLower == "elseif" or ScopeTextLower == "else":
				subprocess.Popen(["hh.exe", xypath + "\\XYplorer.chm::/idh_scripting.htm#idh_scripting_ifthen"])
			elif ScopeTextLower == "while":
				subprocess.Popen(["hh.exe", xypath + "\\XYplorer.chm::/idh_scripting.htm#idh_scripting_whileloops"])
			elif ScopeTextLower == "foreach":
				subprocess.Popen(["hh.exe", xypath + "\\XYplorer.chm::/idh_scripting.htm#idh_scripting_foreachloops"])
			else:
				subprocess.Popen(["hh.exe", xypath + "\\XYplorer.chm::/idh_scripting.htm"])
		elif ScopeName == "source.xys entity.name.function.CommandID.xys":
			# remember to strip 231-236 (New item template customizations) + 303...310 (thumbsizes)
			# + 594,595 (Userprofile name)+ 862-867 (lbl names) + 442...464 (dates) + > 1400 (UDC)
			CmdDict = {
			"#100" : "File | To Clipboard | - submenu -",
			"#101" : "File | To Clipboard | Item Path/Name(s)",
			"#102" : "File | To Clipboard | Item Name(s)",
			"#103" : "File | To Clipboard | Item Path(s)",
			"#113" : "File | To Clipboard | Item Base(s)",
			"#112" : "File | To Clipboard | Item Short Path/Name(s)",
			"#114" : "File | To Clipboard | Item UNC Path/Name(s)",
			"#104" : "File | To Clipboard | Name(s), Bytes, Modified[, Version]",
			"#105" : "File | To Clipboard | Name(s), Bytes, Modified[, Version], Path",
			"#116" : "File | To Clipboard | Name(s), Bytes, Modified[, Version], Path, MD5",
			"#106" : "File | To Clipboard | Compact File Info",
			"#107" : "File | To Clipboard | Extended File Info",
			"#108" : "File | To Clipboard | Large Icon",
			"#109" : "File | To Clipboard | Small Icon",
			"#117" : "File | To Clipboard | Text",
			"#115" : "File | To Clipboard | Image",
			"#110" : "File | To Clipboard | Selected List Row(s)",
			"#111" : "File | To Clipboard | All List Rows",
			"#120" : "File | Rename Special | - submenu -",
			"#121" : "File | Rename Special | Batch Rename...",
			"#122" : "File | Rename Special | RegExp Rename...",
			"#123" : "File | Rename Special | Search and Replace...",
			"#124" : "File | Rename Special | Keep Particular Characters...",
			"#125" : "File | Rename Special | Set Extension...",
			"#147" : "File | Rename Special | Edit Item Names...",
			"#138" : "File | Rename Special | A* A*.aaa",
			"#126" : "File | Rename Special | Aaa Aa.aaa",
			"#127" : "File | Rename Special | aaa aa.aaa",
			"#128" : "File | Rename Special | AAA AA.AAA",
			"#136" : "File | Rename Special | *.aaa",
			"#137" : "File | Rename Special | *.AAA",
			"#129" : "File | Rename Special | Spaces to _",
			"#130" : "File | Rename Special | _ to Spaces",
			"#139" : "File | Rename Special | Remove Diacritics",
			"#131" : "File | Rename Special | Convert to ASCII",
			"#132" : "File | Rename Special | UrlEscape (Space > %20 ...)",
			"#133" : "File | Rename Special | UrlUnescape (%20 > Space ...)",
			"#134" : "File | Rename Special | Unicode to UTF-8",
			"#135" : "File | Rename Special | UTF-8 to Unicode",
			"#140" : "File | Rename Special | Mp3 Special | - submenu -",
			"#141" : "File | Rename Special | Mp3 Special | Filename (Artist - Title.mp3) to ID3 Tag",
			"#142" : "File | Rename Special | Mp3 Special | Filename (Track - Artist - Title.mp3) to ID3 Tag",
			"#143" : "File | Rename Special | Mp3 Special | Filename (Artist - Album - Track - Title.mp3) to ID3 Tag",
			"#158" : "File | Rename Special | Mp3 Special | Filename (Artist - Year - Album - Track - Title.mp3) to ID3 Tag",
			"#144" : "File | Rename Special | Mp3 Special | ID3 Tag to Filename (Artist\Album\Track.mp3)",
			"#145" : "File | Rename Special | Mp3 Special | ID3 Tag to Filename (Artist - Title.mp3)",
			"#146" : "File | Rename Special | Mp3 Special | ID3 Tag to Filename (Album - Track.mp3)",
			"#159" : "File | Rename Special | Mp3 Special | ID3 Tag to Filename (Album - Track - Title.mp3)",
			"#148" : "File | Rename Special | Preview All",
			"#150" : "File | Move/Copy/Backup To | - submenu -",
			"#151" : "File | Move/Copy/Backup To | Move To | - submenu -",
			"#152" : "File | Move/Copy/Backup To | Copy To | - submenu -",
			"#153" : "File | Move/Copy/Backup To | Backup To | - submenu -",
			"#160" : "File | Open Selected Item(s)",
			"#176" : "File | Open with...",
			"#161" : "File | Open with Arguments...",
			"#162" : "File | Open Focused Item",
			"#156" : "File | Open...",
			"#154" : "File | Duplicate | - submenu -",
			"#163" : "File | Duplicate | Copy Here",
			"#164" : "File | Duplicate | Copy Here with Increment",
			"#165" : "File | Duplicate | Copy Here with Current Date",
			"#166" : "File | Duplicate | Copy Here with Last Modified Date",
			"#167" : "File | Duplicate | Copy Here As...",
			"#1042" : "File | Duplicate | Copy Here to New Subfolder...",
			"#1041" : "File | Duplicate | Move Here to New Subfolder...",
			"#169" : "File | Delete",
			"#172" : "File | Rename",
			"#155" : "File | File Special | - submenu -",
			"#168" : "File | File Special | Create Shortcut(s)",
			"#170" : "File | File Special | Delete (No Recycle Bin)",
			"#171" : "File | File Special | Delete (Skip Locked)",
			"#157" : "File | File Special | Delete Long",
			"#179" : "File | File Special | Wipe",
			"#175" : "File | File Special | Swap Names",
			"#1034" : "File | File Special | Set Modified Date to Current",
			"#1073" : "File | File Special | Set Modified Date to Exif",
			"#1074" : "File | File Special | Set Created Date to Exif",
			"#198" : "File | File Special | Display Hash Values",
			"#280" : "File | File Special | Extract Here",
			"#281" : "File | File Special | Add to Zip...",
			"#173" : "File | Properties",
			"#197" : "File | Metadata",
			"#174" : "File | Preview",
			"#177" : "File | Quick File View",
			"#178" : "File | Floating Preview",
			"#182" : "File | Save Settings",
			"#180" : "File | Settings Special | - submenu -",
			"#181" : "File | Settings Special | Load Configuration...",
			"#193" : "File | Settings Special | Save Configuration",
			"#183" : "File | Settings Special | Save Configuration As...",
			"#184" : "File | Settings Special | Save Copy of Configuration As...",
			"#185" : "File | Settings Special | Create Shortcut to this Configuration...",
			"#186" : "File | Settings Special | Save Catalog",
			"#187" : "File | Settings Special | Save User-Defined Commands",
			"#188" : "File | Settings Special | Save Keyboard Shortcuts",
			"#194" : "File | Settings Special | Save Folder View Settings",
			"#195" : "File | Settings Special | Save Tags",
			"#189" : "File | Settings Special | Save Servers",
			"#196" : "File | Settings Special | Backup Application Data Folder...",
			"#190" : "File | Restart without Saving",
			"#191" : "File | Exit without Saving",
			"#192" : "File | Exit",
			"#203" : "Edit | Undo",
			"#204" : "Edit | Redo",
			"#205" : "Edit | Action Log...",
			"#223" : "Edit | Recent File Operations...",
			"#200" : "Edit | Cut",
			"#201" : "Edit | Copy",
			"#202" : "Edit | Paste",
			"#210" : "Edit | Paste Special | - submenu -",
			"#211" : "Edit | Paste Special | Paste Here to New Subfolder...",
			"#273" : "Edit | Paste Special | Paste Here with Path...",
			"#207" : "Edit | Paste Special | Paste Here As...",
			"#212" : "Edit | Paste Special | Paste (Move)",
			"#213" : "Edit | Paste Special | Paste (Copy)",
			"#272" : "Edit | Paste Special | Paste (Backup)",
			"#218" : "Edit | Paste Special | Paste As Shortcut(s)",
			"#208" : "Edit | Paste Special | Paste As Hard Link(s)",
			"#270" : "Edit | Paste Special | Paste As Symbolic Link(s)",
			"#271" : "Edit | Paste Special | Paste As Junction(s)",
			"#275" : "Edit | Paste Special | Paste Extracted",
			"#274" : "Edit | Paste Special | Paste Zipped",
			"#209" : "Edit | Paste Special | Paste Folder Structure",
			"#219" : "Edit | Paste Special | Paste Text Into New File",
			"#206" : "Edit | Paste Special | Paste Image Into New File",
			"#214" : "Edit | Paste Special | Mark Files in Clipboard as 'Cut'",
			"#215" : "Edit | Paste Special | Mark Files in Clipboard as 'Copied'",
			"#216" : "Edit | Paste Special | Edit Files in Clipboard...",
			"#217" : "Edit | Paste Special | Clear Clipboard",
			"#220" : "Edit | Move To...",
			"#221" : "Edit | Copy To...",
			"#222" : "Edit | Backup To...",
			"#225" : "Edit | Compare | - submenu -",
			"#227" : "Edit | Compare | Compare Current File with Previous File",
			"#226" : "Edit | Compare | Compare Current File with File in Clipboard",
			"#228" : "Edit | Compare | Compare Current File on Both Panes",
			"#230" : "Edit | New | - submenu -",
			"#231" : "Edit | New | New Folder Template 1",
			"#232" : "Edit | New | New Folder Template 2",
			"#233" : "Edit | New | New Folder Template 3",
			"#234" : "Edit | New | New Text File Template 1",
			"#235" : "Edit | New | New Text File Template 2",
			"#236" : "Edit | New | New Text File Template 3",
			"#241" : "Edit | New | New Shortcut...",
			"#242" : "Edit | New | New Path...",
			"#243" : "Edit | New | New Folders...",
			"#244" : "Edit | New | New Files...",
			"#240" : "Edit | New Items | - submenu -",
			"#265" : "Edit | Select | - submenu -",
			"#250" : "Edit | Select | Select All",
			"#251" : "Edit | Select | Deselect All",
			"#252" : "Edit | Select | Invert Selection",
			"#257" : "Edit | Select | Restore Selection",
			"#253" : "Edit | Select | Selection Filter...",
			"#254" : "Edit | Select | Select By Selected Type(s)",
			"#255" : "Edit | Select | Select All Files",
			"#256" : "Edit | Select | Select Items...",
			"#258" : "Edit | Select | Selection Stats",
			"#260" : "Edit | Find Files...",
			"#261" : "Edit | Find Now",
			"#262" : "Edit | Repeat Last Search",
			"#264" : "Edit | Search Templates...",
			"#266" : "Edit | Quick Search...",
			"#268" : "Edit | Toggle Quick Search",
			"#267" : "Edit | Repeat Last Quick Search",
			"#263" : "Edit | Show All Items In Branch",
			"#301" : "View | Views | - submenu -",
			"#302" : "View | Views | Details",
			"#303" : "View | Views | Details with Thumbnails #1",
			"#304" : "View | Views | List",
			"#305" : "View | Views | Small Icons",
			"#309" : "View | Views | Large Icons",
			"#313" : "View | Views | Small Tiles",
			"#314" : "View | Views | Large Tiles",
			"#306" : "View | Views | Thumbnails #1",
			"#307" : "View | Views | Thumbnails #2",
			"#308" : "View | Views | Thumbnails #3",
			"#310" : "View | Views | Configure Thumbnails...",
			"#311" : "View | Views | Branch View",
			"#320" : "View | Sort By | - submenu -",
			"#319" : "View | Sort By | Index",
			"#329" : "View | Sort By | Path",
			"#321" : "View | Sort By | Name",
			"#322" : "View | Sort By | Ext",
			"#323" : "View | Sort By | Size",
			"#324" : "View | Sort By | Type",
			"#325" : "View | Sort By | Created",
			"#326" : "View | Sort By | Modified",
			"#327" : "View | Sort By | Accessed",
			"#328" : "View | Sort By | Attr",
			"#334" : "View | Sort By | Len",
			"#335" : "View | Sort By | Label",
			"#337" : "View | Sort By | Tags",
			"#336" : "View | Sort By | Comment",
			"#330" : "View | Sort By | Unsorted",
			"#331" : "View | Sort By | Random Order",
			"#332" : "View | Sort By | Sort Again",
			"#338" : "View | Sort By | Previous Order",
			"#339" : "View | Sort By | Reverse Order",
			"#318" : "View | Sort By | Selected Items to Top",
			"#333" : "View | Sort By | Sort Folders Apart",
			"#312" : "View | Sort By | Show Sort Headers in All Views",
			"#360" : "View | Columns | - submenu -",
			"#361" : "View | Columns | Line Numbers",
			"#384" : "View | Columns | Index",
			"#370" : "View | Columns | Path",
			"#362" : "View | Columns | Name",
			"#363" : "View | Columns | Ext",
			"#364" : "View | Columns | Size",
			"#365" : "View | Columns | Type",
			"#366" : "View | Columns | Created",
			"#367" : "View | Columns | Modified",
			"#368" : "View | Columns | Accessed",
			"#369" : "View | Columns | Attr",
			"#375" : "View | Columns | Len",
			"#379" : "View | Columns | Label",
			"#381" : "View | Columns | Tags",
			"#380" : "View | Columns | Comment",
			"#382" : "View | Columns | Show Columns...",
			"#383" : "View | Columns | Add Column",
			"#371" : "View | Columns | Show All Columns",
			"#372" : "View | Columns | Autosize Columns Now",
			"#373" : "View | Columns | Grow Name Column",
			"#374" : "View | Columns | Shrink Name Column",
			"#377" : "View | Columns | Load Column Layout...",
			"#376" : "View | Columns | Save Column Layout As...",
			"#378" : "View | Columns | Set Line Number Column Width...",
			"#300" : "View | Tab | - submenu -",
			"#340" : "View | Tab | New Tab",
			"#341" : "View | Tab | Default Tab",
			"#358" : "View | Tab | Iconize",
			"#342" : "View | Tab | Rename Tab...",
			"#344" : "View | Tab | Copy Location Term",
			"#346" : "View | Tab | Relocate Tab...",
			"#345" : "View | Tab | Tab History...",
			"#347" : "View | Tab | Set Home",
			"#348" : "View | Tab | Go Home",
			"#349" : "View | Tab | Lock Home Zone",
			"#350" : "View | Tab | Lock Location",
			"#354" : "View | Tab | Set Visual Filter...",
			"#355" : "View | Tab | Toggle Visual Filter",
			"#359" : "View | Tab | Filter By Selection(s)",
			"#356" : "View | Tab | Filter By Selected Extension(s)",
			"#357" : "View | Tab | Filter Out Selected Extension(s)",
			"#385" : "View | Tab | Type Stats and Filter...",
			"#343" : "View | Tab | Restore Last Closed Tab",
			"#352" : "View | Tab | Close All Other Unlocked Tabs",
			"#353" : "View | Tab | Close All Other Tabs",
			"#351" : "View | Tab | Close Tab",
			"#510" : "View | Mini Tree | - submenu -",
			"#489" : "View | Mini Tree | Mini Tree",
			"#511" : "View | Mini Tree | Minimize Tree",
			"#512" : "View | Mini Tree | Load Last Mini Tree",
			"#513" : "View | Mini Tree | Mini Tree From Recent",
			"#515" : "View | Mini Tree | Set as Favorite Mini Tree...",
			"#516" : "View | Mini Tree | Load Favorite Mini Tree",
			"#514" : "View | Mini Tree | Hide Current Folder",
			"#770" : "View | Paper Folders | - submenu -",
			"#771" : "View | Paper Folders | New...",
			"#772" : "View | Paper Folders | Open...",
			"#773" : "View | Paper Folders | Save",
			"#774" : "View | Paper Folders | Save As...",
			"#775" : "View | Paper Folders | Save Copy As...",
			"#776" : "View | Paper Folders | Remove Selected Items",
			"#777" : "View | Paper Folders | Empty Paper Folder",
			"#778" : "View | Paper Folders | Toggle Paper Folder",
			"#470" : "View | Folder View Settings | - submenu -",
			"#471" : "View | Folder View Settings | Enable Folder View Settings",
			"#472" : "View | Folder View Settings | Save Folder View",
			"#478" : "View | Folder View Settings | Restore Folder View",
			"#473" : "View | Folder View Settings | Edit...",
			"#474" : "View | Folder View Settings | Remove",
			"#475" : "View | Folder View Settings | Apply this Folder View Also To...",
			"#476" : "View | Folder View Settings | Define this Folder View as Default",
			"#477" : "View | Folder View Settings | Manage Folder Views...",
			"#1001" : "View | Refresh",
			"#480" : "View | Auto-Refresh",
			"#481" : "View | Suspend Auto-Refresh",
			"#488" : "View | Lock Tree",
			"#482" : "View | Refresh Tree",
			"#484" : "View | Reset Tree",
			"#483" : "View | Refresh Current Folder",
			"#485" : "View | Refresh List",
			"#486" : "View | Reset List",
			"#487" : "View | Calculate Folder Sizes",
			"#490" : "View | Show Items | - submenu -",
			"#491" : "View | Show Items | Show Floppy Drives",
			"#492" : "View | Show Items | Show Hidden Drives",
			"#493" : "View | Show Items | Show Hidden Files and Folders",
			"#494" : "View | Show Items | Show System Files and Folders",
			"#495" : "View | Show Items | Show Junctions",
			"#496" : "View | Show Items | Show Folders in List",
			"#500" : "View | Caches | - submenu -",
			"#501" : "View | Caches | Refresh Thumbnails",
			"#506" : "View | Caches | Refresh Selected Thumbnails",
			"#502" : "View | Caches | Refresh Icons",
			"#505" : "View | Caches | Refresh Environment Variables",
			"#504" : "View | Caches | Update New Items Menu",
			"#520" : "Go | Go to Previous Location",
			"#535" : "Go | Go to Previous Item in List",
			"#521" : "Go | Go to Last Target",
			"#522" : "Go | Top",
			"#523" : "Go | Up",
			"#524" : "Go | Down",
			"#525" : "Go | Breadcrumb...",
			"#526" : "Go | Drives...",
			"#527" : "Go | Back",
			"#528" : "Go | Forward",
			"#529" : "Go | History...",
			"#539" : "Go | Recent Locations...",
			"#530" : "Go | Hotlist...",
			"#538" : "Go | Tablist...",
			"#540" : "Go | Aliases...",
			"#531" : "Go | Go to...",
			"#532" : "Go | Go to from Here...",
			"#533" : "Go | Go to Line...",
			"#534" : "Go | Go to Application Folder",
			"#536" : "Go | Go to Application Data Folder",
			"#550" : "Favorites | Favorite Folders | - submenu -",
			"#551" : "Favorites | Special System Folders | - submenu -",
			"#552" : "Favorites | Special System Folders | Computer",
			"#590" : "Favorites | Special System Folders | Desktop (Virtual)",
			"#591" : "Favorites | Special System Folders | My Documents (Virtual)",
			"#594" : "Favorites | Special System Folders | UserProfile (Virtual)",
			"#592" : "Favorites | Special System Folders | Network (Virtual)",
			"#593" : "Favorites | Special System Folders | Recycle Bin (Virtual)",
			"#553" : "Favorites | Special System Folders | Desktop",
			"#554" : "Favorites | Special System Folders | My Documents",
			"#595" : "Favorites | Special System Folders | UserProfile",
			"#555" : "Favorites | Special System Folders | Favorites",
			"#556" : "Favorites | Special System Folders | Start Menu",
			"#573" : "Favorites | Special System Folders | Program Files",
			"#557" : "Favorites | Special System Folders | Windows Folder",
			"#558" : "Favorites | Special System Folders | System Folder",
			"#559" : "Favorites | Special System Folders | Temp Folder",
			"#571" : "Favorites | Special System Folders | Temporary Internet Files",
			"#572" : "Favorites | Special System Folders | Network Shortcuts",
			"#560" : "Favorites | Special System Folders | Desktop (All Users)",
			"#561" : "Favorites | Special System Folders | My Documents (All Users)",
			"#562" : "Favorites | Special System Folders | Favorites (All Users)",
			"#563" : "Favorites | Special System Folders | Start Menu (All Users)",
			"#564" : "Favorites | Favorite Files | - submenu -",
			"#565" : "Favorites | Favorite Files | Toggle Favorite File",
			"#566" : "Favorites | Toggle Favorite Folder",
			"#567" : "Favorites | Toggle Highlighted Folder",
			"#568" : "Favorites | Toggle Boxed Branch",
			"#569" : "Favorites | Set Highlight Color...",
			"#570" : "Favorites | Set Box Color...",
			"#860" : "Favorites | Labels | - submenu -",
			"#861" : "Favorites | Labels | None",
			"#862" : "Favorites | Labels | [Label #1]",
			"#863" : "Favorites | Labels | [Label #2]",
			"#864" : "Favorites | Labels | [Label #3]",
			"#865" : "Favorites | Labels | [Label #4]",
			"#866" : "Favorites | Labels | [Label #5]",
			"#867" : "Favorites | Labels | [Label #6]",
			"#868" : "Favorites | Labels | [Label #7]",
			"#869" : "Favorites | Labels | [Label #8]",
			"#870" : "Favorites | Labels | [Label #9]",
			"#871" : "Favorites | Labels | [Label #10]",
			"#872" : "Favorites | Labels | [Label #11]",
			"#873" : "Favorites | Labels | [Label #12]",
			"#874" : "Favorites | Labels | [Label #13]",
			"#875" : "Favorites | Labels | [Label #14]",
			"#876" : "Favorites | Labels | [Label #15]",
			"#879" : "Favorites | Apply Last Label",
			"#881" : "Favorites | Add Tags...",
			"#882" : "Favorites | Add Tags by List...",
			"#883" : "Favorites | Add Last Tags",
			"#884" : "Favorites | Edit Tags...",
			"#888" : "Favorites | Edit Tags by List...",
			"#885" : "Favorites | Remove Tags by List...",
			"#886" : "Favorites | Remove All Tags",
			"#880" : "Favorites | Comment...",
			"#887" : "Favorites | Reload Tags Database",
			"#656" : "User | Manage Commands...",
			"#1" : "User | Go To | - submenu -",
			"#2" : "User | Open | - submenu -",
			"#3" : "User | Open With | - submenu -",
			"#4" : "User | Move To | - submenu -",
			"#5" : "User | Copy To | - submenu -",
			"#6" : "User | Backup To | - submenu -",
			"#8" : "User | New | - submenu -",
			"#7" : "User | Rename | - submenu -",
			"#9" : "User | Run Script | - submenu -",
			"#10" : "User | Load Script File | - submenu -",
			"#754" : "Scripting | Run Script...",
			"#755" : "Scripting | Run Script Again",
			"#750" : "Scripting | Step Mode",
			"#752" : "Scripting | Try Script...",
			"#756" : "Scripting | Permanent Variables",
			"#751" : "Scripting | Load Selected Script File",
			"#753" : "Scripting | Load Script File...",
			"#757" : "Scripting | Go to Scripts Folder",
			"#600" : "Tools | Configuration...",
			"#601" : "Tools | Open Configuration File...",
			"#602" : "Tools | Customize Keyboard Shortcuts...",
			"#603" : "Tools | Customize Toolbar...",
			"#604" : "Tools | Customize File Associations...",
			"#605" : "Tools | Customize File Icons...",
			"#390" : "Tools | Customize Tree | - submenu -",
			"#391" : "Tools | Customize Tree | Show Icons",
			"#392" : "Tools | Customize Tree | Show Expansion Icons",
			"#393" : "Tools | Customize Tree | Show Lines",
			"#394" : "Tools | Customize Tree | Mark Favorites (Icon)",
			"#395" : "Tools | Customize Tree | Mark Favorites (Bold)",
			"#396" : "Tools | Customize Tree | Narrow Tree",
			"#397" : "Tools | Customize Tree | Rename On Slow Double-Click",
			"#398" : "Tools | Customize Tree | Apply Highlighting",
			"#399" : "Tools | Customize Tree | Full Row Select",
			"#419" : "Tools | Customize Tree | Tree Path Tracing",
			"#400" : "Tools | Customize List | - submenu -",
			"#401" : "Tools | Customize List | Show Icons",
			"#402" : "Tools | Customize List | Column Drag",
			"#403" : "Tools | Customize List | Multiple Select",
			"#404" : "Tools | Customize List | Full Row Select",
			"#405" : "Tools | Customize List | Highlight Sorted Column",
			"#406" : "Tools | Customize List | Show Line Numbers",
			"#407" : "Tools | Customize List | Autosize Columns",
			"#408" : "Tools | Customize List | Show Grid",
			"#409" : "Tools | Customize List | Highlight Focused Item",
			"#410" : "Tools | Customize List | Highlight Selected Rows",
			"#411" : "Tools | Customize List | Rename On Slow Double-Click",
			"#412" : "Tools | Customize List | Hide Extensions",
			"#413" : "Tools | Customize List | Sticky Selection",
			"#414" : "Tools | Customize List | Manual Sorting",
			"#415" : "Tools | Customize List | Checkbox Selection",
			"#416" : "Tools | Customize List | Ignore Articles When Sorting",
			"#420" : "Tools | Customize List | Size Column Format | - submenu -",
			"#431" : "Tools | Customize List | Size Column Format | Show Folder Sizes",
			"#421" : "Tools | Customize List | Size Column Format | Show Space Used",
			"#422" : "Tools | Customize List | Size Column Format | Raw Bytes Count",
			"#423" : "Tools | Customize List | Size Column Format | Bytes",
			"#424" : "Tools | Customize List | Size Column Format | KB (Rounded Up)",
			"#425" : "Tools | Customize List | Size Column Format | KB",
			"#426" : "Tools | Customize List | Size Column Format | MB",
			"#427" : "Tools | Customize List | Size Column Format | GB",
			"#432" : "Tools | Customize List | Size Column Format | TB",
			"#433" : "Tools | Customize List | Size Column Format | PB",
			"#428" : "Tools | Customize List | Size Column Format | Flexible",
			"#429" : "Tools | Customize List | Size Column Format | Flexible (Rounded Up)",
			"#430" : "Tools | Customize List | Size Column Format | Clusters",
			"#440" : "Tools | Customize List | Date Column Format | - submenu -",
			"#441" : "Tools | Customize List | Date Column Format | Show Age",
			"#453" : "Tools | Customize List | Date Column Format | Show Weekday",
			"#455" : "Tools | Customize List | Date Column Format | Show Milliseconds",
			"#454" : "Tools | Customize List | Date Column Format | Show Times in UTC",
			"#442" : "Tools | Customize List | Date Column Format | System Short Date",
			"#443" : "Tools | Customize List | Date Column Format | System Long Date",
			"#444" : "Tools | Customize List | Date Column Format | dd/mm/yy",
			"#445" : "Tools | Customize List | Date Column Format | dd/mm/yyyy",
			"#446" : "Tools | Customize List | Date Column Format | mm/dd/yy",
			"#447" : "Tools | Customize List | Date Column Format | mm/dd/yyyy",
			"#448" : "Tools | Customize List | Date Column Format | dd-mmm-yy",
			"#449" : "Tools | Customize List | Date Column Format | dd-mmm-yyyy",
			"#450" : "Tools | Customize List | Date Column Format | ISO 8601",
			"#451" : "Tools | Customize List | Date Column Format | ISO Week",
			"#452" : "Tools | Customize List | Date Column Format | Zodiac",
			"#460" : "Tools | Customize List | Date Column Format | System Time",
			"#461" : "Tools | Customize List | Date Column Format | hh:nn",
			"#462" : "Tools | Customize List | Date Column Format | hh:nn am/pm",
			"#463" : "Tools | Customize List | Date Column Format | hh:nn AM/PM",
			"#464" : "Tools | Customize List | Date Column Format | ISO 8601",
			"#465" : "Tools | Customize List | Date Column Format | No Time",
			"#610" : "Tools | List Management | - submenu -",
			"#611" : "Tools | List Management | Address Bar & Go to...",
			"#614" : "Tools | List Management | Portable File Associations...",
			"#653" : "Tools | List Management | Portable File Icons...",
			"#618" : "Tools | List Management | History...",
			"#630" : "Tools | List Management | Mini Tree...",
			"#619" : "Tools | List Management | Move/Copy/Backup To...",
			"#631" : "Tools | List Management | Recent Locations...",
			"#632" : "Tools | List Management | Recently Opened Files...",
			"#634" : "Tools | List Management | Recent Catalogs...",
			"#636" : "Tools | List Management | Recently Included Catalogs...",
			"#650" : "Tools | List Management | Recent Tabsets Pane 1...",
			"#651" : "Tools | List Management | Recent Tabsets Pane 2...",
			"#612" : "Tools | List Management | Favorite Folders...",
			"#613" : "Tools | List Management | Favorite Files...",
			"#627" : "Tools | List Management | Highlighted Folders...",
			"#628" : "Tools | List Management | Boxed Branches...",
			"#629" : "Tools | List Management | Color Filters...",
			"#654" : "Tools | List Management | Instant Color Filters...",
			"#635" : "Tools | List Management | Tag List...",
			"#637" : "Tools | List Management | Tagged Items...",
			"#623" : "Tools | List Management | Selection Filters...",
			"#624" : "Tools | List Management | Visual Filters...",
			"#652" : "Tools | List Management | Power Filters...",
			"#633" : "Tools | List Management | Aliases...",
			"#615" : "Tools | List Management | Find Files: Name...",
			"#616" : "Tools | List Management | Find Files: Location...",
			"#617" : "Tools | List Management | Find Files: Excluded Items...",
			"#638" : "Tools | List Management | Quick Search...",
			"#622" : "Tools | List Management | Rename Special: Batch Rename...",
			"#621" : "Tools | List Management | Rename Special: RegExp Rename...",
			"#620" : "Tools | List Management | Rename Special: Search and Replace...",
			"#625" : "Tools | List Management | Files in Clipboard...",
			"#626" : "Tools | List Management | Servers in Network Folder...",
			"#639" : "Tools | Tools Special | - submenu -",
			"#640" : "Tools | Tools Special | Control Panel...",
			"#641" : "Tools | Tools Special | Open Recycle Bin...",
			"#642" : "Tools | Tools Special | Empty Recycle Bin...",
			"#643" : "Tools | Tools Special | Recycle Bin Stats...",
			"#644" : "Tools | Tools Special | Map Network Drive...",
			"#645" : "Tools | Tools Special | Disconnect Mapped Network Drive...",
			"#646" : "Tools | Tools Special | Reconnect All Mapped Network Drives",
			"#648" : "Tools | Tools Special | Browse for Network Server...",
			"#800" : "Panes | Dual Pane",
			"#801" : "Panes | Horizontal Panes",
			"#802" : "Panes | Toggle Active Pane",
			"#803" : "Panes | Move to Other Pane",
			"#804" : "Panes | Copy to Other Pane",
			"#807" : "Panes | Backup to Other Pane",
			"#805" : "Panes | Move Tab to Other Pane",
			"#806" : "Panes | Copy Tab to Other Pane",
			"#1070" : "Panes | Go to Other Location",
			"#810" : "Panes | Go Here in Other Pane",
			"#811" : "Panes | Swap Locations",
			"#814" : "Panes | Sync Browse",
			"#813" : "Panes | Sync Scroll",
			"#812" : "Panes | Sync Select...",
			"#690" : "Panes | Tabs | - submenu -",
			"#850" : "Tabsets | New...",
			"#851" : "Tabsets | Open...",
			"#856" : "Tabsets | Open As...",
			"#857" : "Tabsets | Revert to Saved",
			"#852" : "Tabsets | Save",
			"#853" : "Tabsets | Save As...",
			"#854" : "Tabsets | Save Copy As...",
			"#855" : "Tabsets | Rename...",
			"#858" : "Tabsets | Go to Tabset Folder",
			"#660" : "Window | Show Address Bar",
			"#661" : "Window | Show Toolbar",
			"#662" : "Window | Show Tab Bar",
			"#671" : "Window | Show Breadcrumb Bar",
			"#670" : "Window | Show Status Bar",
			"#669" : "Window | Show Status Bar Buttons",
			"#663" : "Window | Show Navigation Panels",
			"#668" : "Window | Show Tree",
			"#664" : "Window | Show Catalog",
			"#665" : "Window | Show Info Panel",
			"#680" : "Window | Arrangement | - submenu -",
			"#681" : "Window | Arrangement | Address Bar and Toolbar Stacked",
			"#682" : "Window | Arrangement | Toolbar First",
			"#687" : "Window | Arrangement | Tree and Catalog Stacked",
			"#686" : "Window | Arrangement | Catalog First",
			"#691" : "Window | Arrangement | List Right",
			"#692" : "Window | Arrangement | List Centered",
			"#693" : "Window | Arrangement | List Left",
			"#683" : "Window | Arrangement | Wide Tabs",
			"#685" : "Window | Arrangement | Wide Info Panel",
			"#672" : "Window | Load Layout...",
			"#673" : "Window | Save Layout As...",
			"#700" : "Help | Contents and Index",
			"#701" : "Help | Help on Keyboard Shortcuts",
			"#704" : "Help | Help on Scripting Commands",
			"#702" : "Help | Keyboard Shortcuts on Menu",
			"#703" : "Help | Command IDs on Menu",
			"#705" : "Help | List All Commands...",
			"#710" : "Help | Online Support | - submenu -",
			"#711" : "Help | Online Support | Check for Updates",
			"#712" : "Help | Online Support | What's New?",
			"#713" : "Help | Online Support | Homepage",
			"#714" : "Help | Online Support | Support",
			"#715" : "Help | Online Support | User Forum",
			"#719" : "Help | Online Support | Buy Now",
			"#718" : "Help | Online Support | Upgrade License",
			"#725" : "Help | Update Registration Details...",
			"#728" : "Help | Environment Variables",
			"#727" : "Help | Various Information",
			"#731" : "Help | Select Language...",
			"#729" : "Help | Select Local Language File...",
			"#730" : "Help | Back to English",
			"#732" : "Help | Interface Translation Tool",
			"#726" : "Help | About XYplorer",
			"#1000" : "Miscellaneous | General Functions | Stop",
			"#1005" : "Miscellaneous | General Functions | Open Command Prompt Here",
			"#1061" : "Miscellaneous | General Functions | Toggle Main Menu",
			"#1002" : "Miscellaneous | File Operations | Delete (Skip Locked, No Recycle)",
			"#1054" : "Miscellaneous | File Operations | Nuke",
			"#1055" : "Miscellaneous | File Operations | Delete (Recycle, No Confirmation)",
			"#1056" : "Miscellaneous | File Operations | Move Up",
			"#1053" : "Miscellaneous | File Operations | Open Selected Item(s) with OS Default",
			"#1057" : "Miscellaneous | File Operations | Open Selected Item(s) by Shell",
			"#1004" : "Miscellaneous | File Operations | Open in Browser",
			"#1003" : "Miscellaneous | Preview | Full Screen Preview",
			"#1072" : "Miscellaneous | Preview | Close Preview",
			"#1031" : "Miscellaneous | Preview | Snapshot Video Preview",
			"#1006" : "Miscellaneous | Go To | Go to Focused Item",
			"#1007" : "Miscellaneous | Go To | Go to Focused Item in New Tab",
			"#1008" : "Miscellaneous | Go To | Open Containing Folder in New Background Tab",
			"#1043" : "Miscellaneous | Go To | Open Folder in New Tab",
			"#1062" : "Miscellaneous | Go To | Open Folder in Other Pane",
			"#1063" : "Miscellaneous | Go To | Open Folder in Other Pane in New Tab",
			"#1046" : "Miscellaneous | Go To | Go to Shortcut Target",
			"#1047" : "Miscellaneous | Tree | Create New Subfolder Here",
			"#1009" : "Miscellaneous | Tree | Fully Collapse Drive",
			"#1010" : "Miscellaneous | Tree | Fully Collapse",
			"#1011" : "Miscellaneous | Tree | Fully Expand",
			"#1040" : "Miscellaneous | Tree | Optimize Tree",
			"#1071" : "Miscellaneous | List | Copy List Settings from Other Pane",
			"#1020" : "Miscellaneous | Select Info Panel Tab | Properties",
			"#1021" : "Miscellaneous | Select Info Panel Tab | Version",
			"#1022" : "Miscellaneous | Select Info Panel Tab | Meta",
			"#1023" : "Miscellaneous | Select Info Panel Tab | Preview",
			"#1024" : "Miscellaneous | Select Info Panel Tab | Raw View",
			"#1025" : "Miscellaneous | Select Info Panel Tab | Tags",
			"#1058" : "Miscellaneous | Select Info Panel Tab | Find Files",
			"#1059" : "Miscellaneous | Select Info Panel Tab | Report",
			"#1027" : "Miscellaneous | Window State | Minimize Window",
			"#1028" : "Miscellaneous | Window State | Maximize Window",
			"#1029" : "Miscellaneous | Window State | Restore Window",
			"#1032" : "Miscellaneous | Window State | Center Window",
			"#1013" : "Miscellaneous | Focus Functions | Cycle Focus",
			"#1014" : "Miscellaneous | Focus Functions | Focus Address Bar",
			"#1015" : "Miscellaneous | Focus Functions | Focus Catalog",
			"#1016" : "Miscellaneous | Focus Functions | Focus List",
			"#1017" : "Miscellaneous | Focus Functions | Focus Tree",
			"#1012" : "Miscellaneous | Focus Functions | Move Focused Item Into View",
			"#1033" : "Miscellaneous | Focus Functions | Switch Focus between Files and Folders",
			"#1048" : "Miscellaneous | Focus Functions | Focus First Selected Item",
			"#1049" : "Miscellaneous | Focus Functions | View First Selected Item",
			"#1075" : "Miscellaneous | Focus Functions | Next Type Ahead Match",
			"#1076" : "Miscellaneous | Focus Functions | Previous Type Ahead Match",
			"#1060" : "Miscellaneous | Tab Functions | Open Previous Tab",
			"#1019" : "Miscellaneous | Tab Functions | Cycle Tabs Backward",
			"#1018" : "Miscellaneous | Tab Functions | Cycle Tabs Forward",
			"#1039" : "Miscellaneous | Tab Functions | Cycle Tabs Backward, Delay Browsing",
			"#1038" : "Miscellaneous | Tab Functions | Cycle Tabs Forward, Delay Browsing",
			"#1044" : "Miscellaneous | Tab Functions | Move Tab Left",
			"#1045" : "Miscellaneous | Tab Functions | Move Tab Right",
			"#1026" : "Miscellaneous | Find Files | Open Find Files and Reset",
			"#1030" : "Miscellaneous | Find Files | Search All Tabs",
			"#1035" : "Miscellaneous | Timestamp | Set Created Date to Current",
			"#1036" : "Miscellaneous | Timestamp | Set Accessed Date to Current",
			"#1037" : "Miscellaneous | Timestamp | Set Modified Date to Created Date",
			"#1077" : "Miscellaneous | Various | Toggle Instant Color Filter",
			"#1078" : "Miscellaneous | Various | Reopen List Management",
			"#666" : "Miscellaneous | Layout | Last Size/Minimize Info Panel",
			"#667" : "Miscellaneous | Layout | Maximize/Minimize Info Panel"
			}
			if ScopeText in CmdDict :
				sublime.status_message(CmdDict[ScopeText])
			else:
				sublime.status_message(ScopeText + ": Command ID not recognized")

		else:
			# tofix
			sublime.run_command("move_to", {"to": "hardeol"})        # Add new line
			sublime.run_command("insert", {"characters": "\n"})      # Add new line

# ::/idh_scripting_comref.htm#idh_sc_folderreport
# mk:@MSITStore:C:\XYplorer\XYplorer.chm::/idh_scripting_comref.htm#idh_sc_getpathcomponent
