<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>XYplorer</string>
	<key>scopeName</key>
	<string>source.xys</string>
	<key>fileTypes</key>
		<array>
		<string>xys</string>
		<string>xyi</string>
		<string>inc</string>
		</array>

	<key>patterns</key>
	<array>

		<dict>
			<key>name</key>
			<string>comment.line.xys</string>
			<key>match</key>
			<string>//.*</string> <!-- removed url detection, unnecessary -->
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.xys</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
		</dict>

		<dict>
			<key>name</key>
			<string>entity.name.function.xys</string>   <!-- native functions,eg: abs(num) -->
			<key>match</key>
			<string>(?i)\b(?:abs|asc|attrstamp|base64encode|base64decode|caller|catalogreport|ceil|cell|chr|colorfilter|columnlayout|compare|confirm|copier|ctbicon|ctbname|ctbstate|datediff|eval|exists|extracttext|extratag|filesequal|filesize|filetype|floor|folderreport|foldersize|format|formatbytes|formatdate|formatlist|get|getinfo|getkey|getpathcomponent|getsectionlist|gettoken|gettokenindex|hash|hexdump|hextodec|html|input|inputfile|inputfolder|inputselect|isset|isunicode|listfolder|listpane|loadlayout|md5|new|now|paperfolder|popupmenu|property|quote|rand|readfile|readurl|recase|regexmatches|regexreplace|renameitem|replace|replacelist|report|resolvepath|round|row|runret|savethumb|self|setcolumns|seticons|setlayout|strlen|strpos|strrepeat|substr|sync|tab|tabset|tagitems|taglist|toolbar|trim|tweak|urldecode|urlencode|utf8decode|utf8encode|writefile|zip_add|zip_extract|zip_list)(?=\s*\()</string>
		</dict>

		<dict>
			<key>name</key>
			<string>entity.name.function.xys</string>  <!-- native commands,eg: beep freq,time -->
			<key>match</key>
			<string>(?i)\b(?:assert|backupto|beep|box|br|button|call|catalogload|charview|comparehash|comment|copy|copyas|copydata|copyitem|copytext|copyto|delete|download|echo|edittags|end|exist|exit|filter|focus|fresh|freshhere|global|goto|hashlist|help|highlight|incr|info|internetflags|load|loadsearch|loadtree|logtofile|makecoffee|moveas|moveto|msecs|msg|open|openwith|perm|popupmainmenu|quickfileview|readpv|releaseglobals|rename|return|rotate|rtfm|run|savesettings|screen|sel|selectitems|selfilter|seltab|sendkeys|set|setkey|setting|settingp|showhash|showshellprops|snippet|sortby|sound|status|sub|swapnames|sysicons|tag|text|timestamp|unset|unthumb|userbutton|wait|winpos|winsize|wipe|writepv)\b</string>
		</dict>

		<dict>
			<key>name</key>
			<string>entity.name.function.CommandID.xys</string>
			<key>match</key>
			<string>(?&lt;!\w)#\d{3,4}(?!\w)</string>
		</dict>

		<dict>
			<key>name</key>
			<string>variable.parameter.xys</string>
			<key>match</key>
			<string>\|:\w+|(?i)\$\w+|\{:(Text|Image|Photo|Audio|Video|Media|Font|Vector|Web|Office|Archive|Executable)\}</string>
		</dict>

		<dict>
			<key>name</key>
			<string>variable.parameter.native.xys</string>
			<key>match</key>
			<string>&lt;[ .,\*\|\#\:\-\+\w]+&gt;|%[A-Za-z0-9()_-]+%</string> <!-- removed {templates}, consider them as strings -->
		</dict>

		<dict>
			<key>name</key>
			<string>keyword.control.xys</string>
			<key>match</key>
			<string>(?i)\b(?:step|unstep|break|continue|while|if|else|elseif|foreach)\b</string>
		</dict>

		<dict>
			<key>name</key>
			<string>keyword.control.xys</string>
			<key>match</key>
			<string>(?i)^\s*include\b</string> <!-- INCLUDE may be indented -->
		</dict>

		<dict>
			<key>comment</key>
			<string>namespace definition</string>
			<key>match</key>
			<string>(?i)^(namespace)\s+(\w+)$</string> <!-- namespace cmd must be unindented -->
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.xys</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.xys</string>
				</dict>
			</dict>
		</dict>

		<dict>
			<key>name</key>
			<string>constant.numeric.xys</string>
			<key>match</key>
			<string>(?&lt;!\w)-?\d+[/%\.]?(?!\w)</string>  <!-- Original Regex: (?<!\w)-?\d+[/%\.]?(?!\w) Simpler RegEx: \b(\d+)\b -->
		</dict>

		<dict>
			<key>name</key>
			<string>keyword.operator</string>
			<key>match</key>
			<string>([\!)(){},]|[\*\+-\/\^%]|\sUnLikeI?\s|\sLikeI?\s|\sAND\s|\sOR\s|\sXOR\s|\sNOT\s|\s\|\|\s|\B-\B|=|\s+\.\s+|(?&lt;!\w)&gt;|&lt;(?![\w&lt;])|\B&amp;?\W&amp;\B)</string>   <!--Match:  ! = || LikeI? UnLikeI? AND OR NOT XOR < > && -->
		</dict>

		<dict>
			<key>name</key>
			<string>string.unquoted.nowdoc</string> <!-- radical nowdoc -->
			<key>begin</key>
			<string>&lt;{3}'([^#].*)'$</string>
			<key>end</key>
			<string>^\1;?$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.unquoted.nowdoc</string> <!-- regular nowdoc -->
			<key>begin</key>
			<string>&lt;{3}#'(.*)'$</string>
			<key>end</key>
			<string>#\1</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.unquoted.heredoc</string> <!-- radical heredoc -->
			<key>begin</key>
			<string>&lt;{3}(#.*)$</string>
			<key>end</key>
			<string>\1</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.unquoted.heredoc</string> <!-- regular heredoc -->
			<key>begin</key>
			<string>&lt;{3}([^#](.*))$</string>
			<key>end</key>
			<string>^\1;?$</string>
		</dict>

		<dict>
			<key>comment</key>
			<string>matches subscript caption</string>
			<key>name</key>
			<string>string</string>
			<key>match</key>
			<string>^\s*(&quot;.*?&quot;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.class.scriptcaption.xys</string>
				</dict>
			</dict>
		</dict>
		<!-- string scope defined afterwards so it does not consume subscriptcaption region -->

		<dict>
			<key>name</key>
			<string>string</string>
			<key>match</key>
			<string>(&quot;|')(.*?)\1</string>
		</dict>

		<dict>
			<key>comment</key>
			<string>User-Defined function declaration</string>
			<key>match</key>
			<string>(?i)^\s*(function)\s+([\w:]+)(?=\s*\()</string>
			<!-- function can be indented. Removed final (.+) to hilite pararms -->
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.xys</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.class.UDF.xys</string>
				</dict>
			</dict>
		</dict>

		<dict>
			<key>comment</key>
			<string>Allow Contextual Help to Goto Definition</string>
			<key>name</key>
			<string>entity.name.function.UDF.xys</string>
			<key>match</key>
			<string>(?&lt;=\s)[\w:]+(?=\s*\()</string> <!-- (?<=\s).+(?=\() -->
		</dict>


	</array>
</dict>
</plist>
